// src/csvTemplates.js
export const templates = {
  rapsodo: {
    "BallSpeed": "ball_speed",
    "LaunchAngle": "launch_angle",
    "VLA": "vla",
    "PeakHeight": "peak_height",
    "ApexHeight": "peak_height",
    "DescentAngle": "descent_angle",
    "SpinRate": "spin_rate",
    "CarryDistance": "carry_distance",
    "TotalDistance": "total_distance",
    "Offline": "side_total",
    "ClubSpeed": "club_speed",
    // add other known headers
  },
  gspro: {
    "BallSpeed": "ball_speed",
    "LaunchAngle": "launch_angle",
    "VLA": "vla",
    "PeakHeight": "peak_height",
    "ApexHeight": "peak_height",
    "Decent": "descent_angle",
    "Descent": "descent_angle",
    "Spin": "spin_rate",
    "BackSpin": "back_spin",
    "SideSpin": "side_spin",
    "Carry": "carry_distance",
    "TotalDistance": "total_distance",
    "Offline": "side_total",
    "Club": "club",
    "ClubSpeed": "club_speed",
    // GSPRO specific mappings based on actual export
    "HLA": "hla",
    "DistanceToPin": "distance_to_pin",
    "rawSpinAxis": "raw_spin_axis",
    "rawCarryGame": "raw_carry_game",
    "rawCarryLM": "raw_carry_lm",
    "Path": "path",
    "AoA": "aoa",
    "FaceToTarget": "face_to_target",
    "FaceToPath": "face_to_path",
    "Lie": "lie",
    "Loft": "loft",
    "DynamicLoft": "dynamic_loft",
    "CR": "cr",
    "HI": "hi",
    "VI": "vi",
    "SmashFactor": "smash_factor",
  },
  foresight: {
    "BallSpeed": "ball_speed",
    "LaunchAngle": "launch_angle",
    "VLA": "vla",
    "PeakHeight": "peak_height",
    "ApexHeight": "peak_height",
    "DescentAngle": "descent_angle",
    "SpinRate": "spin_rate",
    "CarryDistance": "carry_distance",
    "TotalDistance": "total_distance",
    "Offline": "side_total",
    "ClubSpeed": "club_speed",
  },
  trackman: {
    "Ball_Spd": "ball_speed",
    "Launch_Ang": "launch_angle",
    "VLA": "vla",
    "Peak_Height": "peak_height",
    "Apex_Height": "peak_height",
    "Descent_Ang": "descent_angle",
    "Spin": "spin_rate",
    "Carry": "carry_distance",
    "Total": "total_distance",
    "Offline": "side_total",
    "Club_Spd": "club_speed",
  },
};
